from pathlib import Path

ROOT = Path.cwd()


def write(path: str, text: str) -> None:
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text.strip() + "\n", encoding="utf-8")


def append_once(path: str, marker: str, text: str) -> None:
    p = ROOT / path
    current = p.read_text(encoding="utf-8") if p.exists() else ""
    if marker not in current:
        p.write_text(current.rstrip() + "\n\n" + text.strip() + "\n", encoding="utf-8")


write(
    "context/18_EVALUATION_BASELINES_SPEC.md",
    """
# Phase 11: Evaluation, Baselines, and Human-Trace Import v1 Spec

## Status

Phase 11 implements the first evaluation and baseline-comparison packet.

This phase does not finalize an artifact.

This phase does not claim real human validation.

This phase does not run a live human study.

## Goal

Create an evaluation packet around a candidate artifact produced by the source-to-artifact production run.

The evaluation packet should represent:

candidate artifact
â†’ baseline artifacts
â†’ blind comparison
â†’ reader-state transition comparison
â†’ human-trace import or fixture trace
â†’ baseline comparison report
â†’ evaluation gate report
â†’ evaluation packet

The purpose is to make comparison and reader-state evidence first-class before any final artifact or paper claim.

## Inputs

Default inputs should be deterministic fixtures and the latest fake production packet.

Optional explicit input path may be supported later, but tests must use fixtures only.

## Required CLI behavior

Add a command such as:

abi evaluation demo --client fake

and optionally:

abi evaluation demo --client openai --allow-live-model --max-model-calls 12

Rules:

- fake client mode must not require API key
- openai client mode must require --allow-live-model
- openai client mode must require OPENAI_API_KEY
- deterministic demos must remain unchanged
- evaluation packet output must use unique packet directories
- accepted parsed model artifacts must include model_call_id where model-shaped outputs are used
- all artifacts must be registered through the artifact registry
- finalization must remain fail-closed

## Required artifacts

The evaluation packet should produce artifact types equivalent to:

- evaluation_subject
- evaluation_candidate_artifact_ref
- evaluation_direct_prompt_baseline
- evaluation_best_of_n_baseline_summary
- evaluation_blind_comparison_protocol
- evaluation_blind_comparison_result
- evaluation_human_trace_import
- evaluation_reader_state_transition_comparison
- evaluation_baseline_comparison_report
- evaluation_gate_report
- evaluation_packet

Exact artifact names may differ if aligned with existing conventions.

## Candidate and baseline rules

The candidate artifact must remain marked:

- non_final: true
- not_human_validated: true
- not_finalization_eligible: true

Baselines must be clearly marked as fixture/fake unless generated by an explicit guarded live path.

No baseline result may be treated as real external validation in this phase.

## Human trace rules

Phase 11 may import a fixture human trace from fixtures/human_calibration/ or create a new deterministic fixture trace.

The trace must be marked:

- fixture_only: true
- not_real_validation: true

No live survey integration.

No real human-study claim.

## Model-call behavior

The fake evaluation run may use fake model-shaped workers for baseline summaries or comparison reports.

Every model-shaped output must be schema-validated before parsed artifact registration.

Accepted parsed model artifacts must include:

- schema_version
- artifact_type
- run_id
- lineage_id
- parent_ids
- created_by
- fixture_only
- model_call_id
- payload

Invalid model outputs must not create parsed artifacts.

Client failures must be recorded.

## Budget guard

Add or reuse a simple max-call guard.

Suggested default:

--max-model-calls 12

If execution would exceed the budget, the command must refuse or stop with a structured error.

## Required gate behavior

Phase 11 gate report evaluates only the evaluation packet scaffold.

It must not claim that Abi has beaten baselines.

It must not claim a phase shift.

It must not satisfy finalization gates.

Finalization must remain fail-closed.

## Prohibited

- no final artifact claim
- no phase-shift claim
- no real human-study claim
- no live human-study automation
- no dashboard
- no multi-lineage tournament
- no agent loops
- no automatic OpenAI calls
- no finalization semantic changes
- no SKILL.md
- no broad refactor

## Acceptance criteria

Phase 11 is complete only when:

- ruff passes
- pytest passes
- deterministic demos still work
- fake evaluation demo works
- openai evaluation demo refuses without --allow-live-model
- openai evaluation demo refuses without OPENAI_API_KEY
- evaluation packet contains candidate, baselines, blind comparison, human-trace fixture/import, comparison report, gate report
- fixture-only and not-real-validation flags are present where required
- candidate remains non-final
- parent IDs are populated where appropriate
- max-call budget is enforced
- finalization remains fail-closed
""",
)

write(
    "context/plans/PHASE_11_EVALUATION_BASELINES.md",
    """
# Phase 11 Evaluation, Baselines, and Human-Trace Import ExecPlan

## Goal

Implement the first evaluation packet around a production candidate artifact.

This phase should create comparison evidence scaffolding without claiming real validation.

## Scope

Add:

- evaluation orchestrator
- fake-client evaluation path
- optional guarded OpenAI evaluation path
- baseline fixture generation or import
- candidate artifact reference
- blind comparison protocol/result
- human-trace import fixture
- reader-state transition comparison
- baseline comparison report
- evaluation gate report
- evaluation packet
- max model-call budget guard
- CLI command
- tests

## Likely files

Likely new files:

src/abi/modules/evaluation.py
tests/test_evaluation.py
tests/test_evaluation_cli.py

Likely updated files:

src/abi/cli.py
src/abi/controller/state.py
src/abi/model_schemas.py
README.md

Optional fixtures:

fixtures/evaluation/direct_prompt_baseline.md
fixtures/evaluation/human_trace_fixture.json

## CLI

Preferred command:

abi evaluation demo --client fake

Optional guarded live path:

abi evaluation demo --client openai --allow-live-model --max-model-calls 12

The fake path must require no API key.

The OpenAI path must refuse unless --allow-live-model is passed and OPENAI_API_KEY is set.

## Required output packet

The evaluation packet must expose:

1. evaluation_subject
2. candidate_artifact_ref
3. direct_prompt_baseline
4. best_of_n_baseline_summary
5. blind_comparison_protocol
6. blind_comparison_result
7. human_trace_import
8. reader_state_transition_comparison
9. baseline_comparison_report
10. evaluation_gate_report
11. evaluation_packet

## Tests

Tests must verify:

- all previous tests still pass
- deterministic demos remain unchanged
- fake evaluation demo succeeds
- evaluation packet produces required concepts
- candidate artifact is marked non-final
- fixture human trace is marked fixture_only and not_real_validation
- baseline artifacts are marked fixture/fake unless live path is explicitly selected
- parent IDs are populated where appropriate
- packet directory is unique per invocation
- max-call budget is enforced
- openai client path refuses without --allow-live-model
- openai client path refuses without OPENAI_API_KEY
- finalization remains fail-closed

## Manual live smoke test

Manual OpenAI evaluation smoke test is optional and should not be run by Codex.

It should require:

- OPENAI_API_KEY set
- --allow-live-model passed
- max model calls explicitly set

## Done means

Phase 11 is done when an evaluation packet can be generated around a production candidate, baselines and human-trace fixtures are represented as artifacts, and no final validation claim is made.
""",
)

write(
    "fixtures/evaluation/direct_prompt_baseline.md",
    """
# Direct Prompt Baseline Fixture

This is fixture baseline text, not a live model output.

The table remains in the morning. Its persistence suggests memory, continuity, and the possibility of return. The object becomes a symbol for endurance after absence.
""",
)

write(
    "fixtures/evaluation/human_trace_fixture.json",
    """
{
  "fixture_only": true,
  "not_real_validation": true,
  "reader_id": "fixture_reader_eval_001",
  "protocol": "evaluation_trace_fixture_v1",
  "candidate_label": "candidate_A",
  "first_read": {
    "literal_memory": ["table", "morning", "stillness", "return"],
    "opening_interpretation": "A plain statement of persistence with mild unease.",
    "retained_images": ["table", "morning light"],
    "attention_drops": [],
    "confusion_points": []
  },
  "reread": {
    "changed_opening_interpretation": "The opening now reads as a germ for return without erasure.",
    "changed_words": ["still", "morning"],
    "details_that_gained_force": ["table", "surface", "remaining"],
    "unsupported_depth_flags": []
  },
  "comparison": {
    "preferred_label": "candidate_A",
    "confidence": 0.65,
    "reason": "Fixture comparison says candidate A has stronger opening transformation than the baseline."
  }
}
""",
)

append_once(
    "context/00_CONTEXT_INDEX.md",
    "Phase 11 reads:",
    """
## Phase 11 reads:

For Phase 11, read:

1. AGENTS.md
2. context/00_ARCHITECTURE_FREEZE.md
3. context/00_CONTEXT_INDEX.md
4. context/01_PROJECT_BRIEF.md
5. context/02_ENGINEERING_CONTRACT.md
6. context/05_FAIL_CLOSED_CONTROLLER_SPEC.md
7. context/06_DATA_MODEL.md
8. context/08_GATES_AND_EVALUATION.md
9. context/10_HUMAN_CALIBRATION_SPEC.md
10. context/11_MODEL_READINESS_CONSOLIDATION_SPEC.md
11. context/12_MODEL_DRIVER_FAKE_CLIENT_SPEC.md
12. context/17_SOURCE_TO_ARTIFACT_PRODUCTION_RUN_SPEC.md
13. context/18_EVALUATION_BASELINES_SPEC.md
14. context/plans/PHASE_11_EVALUATION_BASELINES.md

Phase 11 implements evaluation, baselines, and human-trace import only.
""",
)

print("Phase 11 Evaluation/Baselines context files created.")
print("Next:")
print("  git status")
print("  git add context fixtures tools/setup_context_scripts/setup_phase11_context.py")
print('  git commit -m "Add Phase 11 evaluation baselines frozen context"')
print("  git push")
